# Generated by Django 6.1 on 2026-08-13 01:17

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual'), ('SYNCED', 'Synced')], max_length=10)),
                ('is_ungrouped', models.BooleanField(default=False, editable=False)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_account_id', models.CharField(blank=True, max_length=255)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('system_category', models.CharField(choices=[('SECURITY', 'Security'), ('CASH', 'Cash'), ('REAL_ESTATE', 'Real estate'), ('VEHICLE', 'Vehicle'), ('COMMODITY', 'Commodity'), ('COLLECTIBLE', 'Collectible'), ('PRIVATE_ASSET', 'Private asset'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_asset_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('system_category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('native_currency', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO 4217 code.', regex='^[A-Z]{3}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('market_linked', models.BooleanField(default=False)),
                ('market_symbol', models.CharField(blank=True, max_length=64)),
                ('market_exchange', models.CharField(blank=True, max_length=64)),
                ('market_identity', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='portfolios.assettype')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SYNCED', 'Synced')], default='MANUAL', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, default=1, max_digits=28)),
                ('average_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('cost_currency', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO 4217 code.', regex='^[A-Z]{3}$')])),
                ('manual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('provider_value', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('provider_value_as_of', models.DateTimeField(blank=True, null=True)),
                ('provider_position_id', models.CharField(blank=True, max_length=255)),
                ('provider_security_id', models.CharField(blank=True, max_length=255)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolios.asset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolios.group')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('base_currency', models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO 4217 code.', regex='^[A-Z]{3}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolios.portfolio'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', True)), name='unique_system_asset_type_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), condition=models.Q(('owner__isnull', False)), name='unique_user_asset_type_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='holding_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__isnull', True), ('average_cost__gte', 0), _connector='OR'), name='holding_average_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('manual_value__isnull', True), ('manual_value__gte', 0), _connector='OR'), name='holding_manual_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ungrouped', True)), fields=('portfolio',), name='unique_portfolio_ungrouped_group'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('is_ungrouped', False), ('mode', 'SYSTEM'), _connector='OR'), name='ungrouped_group_must_be_system'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'SYNCED'), models.Q(('provider', ''), _negated=True), models.Q(('provider_account_id', ''), _negated=True)), fields=('portfolio', 'provider', 'provider_account_id'), name='unique_synced_provider_account_per_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('market_linked', True), models.Q(('market_symbol', ''), ('market_exchange', ''), ('market_identity', {})), _connector='OR'), name='manual_asset_has_no_market_fields'),
        ),
    ]
