# Generated by Django 6.1 on 2026-08-13 01:18

from django.db import migrations


BUILTIN_ASSET_TYPES = (
    ("Stock", "SECURITY"),
    ("ETF", "SECURITY"),
    ("Fund", "SECURITY"),
    ("Bond", "SECURITY"),
    ("Cash", "CASH"),
    ("Deposit", "CASH"),
    ("Home", "REAL_ESTATE"),
    ("Rental Property", "REAL_ESTATE"),
    ("Land", "REAL_ESTATE"),
    ("Car", "VEHICLE"),
    ("Motorcycle", "VEHICLE"),
    ("Boat", "VEHICLE"),
    ("Precious Metal", "COMMODITY"),
    ("Collectible", "COLLECTIBLE"),
    ("Private Company", "PRIVATE_ASSET"),
    ("Private Fund", "PRIVATE_ASSET"),
    ("Other", "OTHER"),
)


def seed_builtin_asset_types(apps, schema_editor):
    AssetType = apps.get_model("portfolios", "AssetType")
    for name, category in BUILTIN_ASSET_TYPES:
        AssetType.objects.get_or_create(
            owner=None,
            name=name,
            defaults={"system_category": category, "is_active": True},
        )


def remove_builtin_asset_types(apps, schema_editor):
    AssetType = apps.get_model("portfolios", "AssetType")
    AssetType.objects.filter(
        owner__isnull=True,
        name__in=[name for name, _ in BUILTIN_ASSET_TYPES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_builtin_asset_types, remove_builtin_asset_types),
    ]
