# Generated by Django 6.1 on 2026-08-14 01:17

from django.db import migrations, models


def classify_existing_market_links(apps, schema_editor):
    Asset = apps.get_model("portfolios", "Asset")
    Asset.objects.filter(market_linked=True).update(market_data_status="LINKED")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_seed_builtin_asset_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='market_data_status',
            field=models.CharField(choices=[('UNLINKED', 'Unlinked'), ('LINKED', 'Linked'), ('NEEDS_RELINK', 'Needs relink'), ('UNAVAILABLE', 'Unavailable')], default='UNLINKED', max_length=16),
        ),
        migrations.RunPython(
            classify_existing_market_links,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('market_linked', False), ('market_data_status', 'UNLINKED')), models.Q(('market_linked', True), models.Q(('market_data_status', 'UNLINKED'), _negated=True), models.Q(('market_symbol', ''), _negated=True)), _connector='OR'), name='market_link_status_consistent'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'SYNCED'), models.Q(('provider_position_id', ''), _negated=True)), fields=('group', 'provider_position_id'), name='unique_synced_provider_position_in_group'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'SYNCED'), ('provider_position_id', ''), models.Q(('provider_security_id', ''), _negated=True)), fields=('group', 'provider_security_id'), name='unique_synced_provider_security_without_position'),
        ),
    ]
