# Generated by Django 6.1 on 2026-08-14 12:10

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_asset_market_data_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('target_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='portfolios.theme')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ThemeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_assignment', to='portfolios.holding')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portfolios.theme')),
            ],
        ),
        migrations.CreateModel(
            name='ViewBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('data_source', models.CharField(choices=[('HOLDINGS', 'Holdings'), ('INCOME', 'Income'), ('THEMES', 'Themes'), ('GROUPS', 'Groups')], max_length=12)),
                ('presentation', models.CharField(choices=[('TABLE', 'Table'), ('LIST', 'List'), ('SUMMARY', 'Summary')], max_length=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=12)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='portfolios.portfolioview')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='IncomeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('INTEREST', 'Interest'), ('ROYALTY', 'Royalty'), ('STAKING', 'Staking'), ('DIVIDEND', 'Dividend'), ('OTHER', 'Other')], max_length=12)),
                ('amount_per_payment', models.DecimalField(decimal_places=2, max_digits=24)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO 4217 code.', regex='^[A-Z]{3}$')])),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMIANNUAL', 'Semiannual'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], max_length=12)),
                ('payments_per_year', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_rules', to='portfolios.holding')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_per_payment__gte', 0)), name='income_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('payments_per_year__isnull', True), ('payments_per_year__gt', 0), _connector='OR'), name='income_payments_per_year_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolioview',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('portfolio'), name='unique_portfolio_view_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('portfolio'), name='unique_theme_name_per_portfolio_ci'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(condition=models.Q(('target_percentage__isnull', True), models.Q(('target_percentage__gte', 0), ('target_percentage__lte', 100)), _connector='OR'), name='theme_target_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='viewblock',
            constraint=models.UniqueConstraint(fields=('view', 'position'), name='unique_block_position_per_view'),
        ),
        migrations.AddConstraint(
            model_name='viewblock',
            constraint=models.CheckConstraint(condition=models.Q(('width__gte', 1), ('width__lte', 12)), name='view_block_width_range'),
        ),
    ]
