# Generated by Django 6.1 on 2026-08-14 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_portfolioview_theme_themeassignment_viewblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Country must be a two-letter ISO 3166-1 code.', regex='^[A-Z]{2}$')]),
        ),
        migrations.AddField(
            model_name='asset',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portfolioview',
            name='scope_mode',
            field=models.CharField(choices=[('ALL', 'All holdings'), ('SELECTED', 'Selected holdings')], default='ALL', max_length=10),
        ),
        migrations.CreateModel(
            name='ViewHoldingSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_selections', to='portfolios.holding')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_selections', to='portfolios.portfolioview')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('view', 'holding'), name='unique_holding_selection_per_view')],
            },
        ),
    ]
