"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-development-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'subscriptions.apps.SubscriptionsConfig',
    'integrations.market_data.apps.MarketDataConfig',
    'integrations.brokerage.apps.BrokerageConfig',
    'portfolios.apps.PortfoliosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = "users.User"


# External data integrations

REDIS_URL = os.environ.get("REDIS_URL", "")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tracking-app-default",
    },
    "market_data": (
        {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "tracking-app",
            "TIMEOUT": 300,
            "OPTIONS": {
                "socket_connect_timeout": int(os.environ.get("REDIS_CONNECT_TIMEOUT", "2")),
                "socket_timeout": int(os.environ.get("REDIS_SOCKET_TIMEOUT", "2")),
            },
        }
        if REDIS_URL
        else {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "tracking-app-market-data",
        }
    ),
}

MARKET_DATA = {
    "FMP_API_KEY": os.environ.get("FMP_API_KEY", ""),
    "FMP_BASE_URL": os.environ.get(
        "FMP_BASE_URL", "https://financialmodelingprep.com/stable"
    ),
    "HTTP_TIMEOUT": int(os.environ.get("MARKET_DATA_HTTP_TIMEOUT", "10")),
    "CACHE_ALIAS": "market_data",
    "TTLS": {
        "SEARCH": int(os.environ.get("MARKET_SEARCH_TTL", "300")),
        "SEARCH_STALE": int(os.environ.get("MARKET_SEARCH_STALE_TTL", "86400")),
        "QUOTE": int(os.environ.get("MARKET_QUOTE_TTL", "60")),
        "QUOTE_STALE": int(os.environ.get("MARKET_QUOTE_STALE_TTL", "86400")),
        "PROFILE": int(os.environ.get("MARKET_PROFILE_TTL", "86400")),
        "PROFILE_STALE": int(os.environ.get("MARKET_PROFILE_STALE_TTL", "604800")),
        "DIVIDENDS": int(os.environ.get("MARKET_DIVIDENDS_TTL", "21600")),
        "DIVIDENDS_STALE": int(
            os.environ.get("MARKET_DIVIDENDS_STALE_TTL", "604800")
        ),
        "NEGATIVE": int(os.environ.get("MARKET_NEGATIVE_TTL", "120")),
    },
}

BROKERAGE = {
    "SNAPTRADE_CLIENT_ID": os.environ.get("SNAPTRADE_CLIENT_ID", ""),
    "SNAPTRADE_CONSUMER_KEY": os.environ.get("SNAPTRADE_CONSUMER_KEY", ""),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND_PATH = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
MAILERS = {"default": {"BACKEND": EMAIL_BACKEND_PATH}}
if EMAIL_BACKEND_PATH == "django.core.mail.backends.smtp.EmailBackend":
    MAILERS["default"]["OPTIONS"] = {
        "host": os.environ.get("EMAIL_HOST", "localhost"),
        "port": int(os.environ.get("EMAIL_PORT", "587")),
        "username": os.environ.get("EMAIL_HOST_USER", ""),
        "password": os.environ.get("EMAIL_HOST_PASSWORD", ""),
        "use_tls": os.environ.get("EMAIL_USE_TLS", "true").lower() == "true",
        "use_ssl": os.environ.get("EMAIL_USE_SSL", "false").lower() == "true",
        "timeout": int(os.environ.get("EMAIL_TIMEOUT", "10")),
    }

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@tracking-app.local")
PASSWORD_RESET_CONFIRM_URL = os.environ.get(
    "PASSWORD_RESET_CONFIRM_URL",
    "http://localhost:3000/reset-password?uid={uid}&token={token}",
)

# Secure production defaults are enabled automatically when DEBUG is false.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", str(not DEBUG)).lower() == "true"
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
